# Height of bar
height = 20

# Margin around window
margin = 5

# Font size on bar
font_size = 10

# Font family of text
font_family = "monospace"

# Colors for font
font_color = 0xabb2bf
font_active_color = 0x282c34

# Colors for bar
background_color = 0x282c34
background_active_color = 0x56b6c2

workspace_width = 30
